config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  resources :users
  resources :sessions

  resources :galleries, shallow: true do
    get 'count', on: :member
    resources :photos do
      collection do
        put 'bulkupdate'
      end
      resources :comments
    end
  end

  # match 'photos/update_field/:id/:field' => 'photos#update_field', :as => :caption
  post 'photos/increment'

  get '/:private_key', to: 'galleries#show'

  root to: 'galleries#index'
end

app/models/photo.rb
class Photo < ApplicationRecord
  include Rails.application.routes.url_helpers

  belongs_to :gallery
  has_many :comments, dependent: :delete_all
  before_save :set_defaults

  mount_uploader :img, ImageUploader

  def increment
    self.views += 1
    save
  end

  def extract_exif(image)
    if image['EXIF:DateTimeOriginal']
      begin
        self.photo_at = DateTime.strptime(image['EXIF:DateTimeOriginal'].strip, '%Y:%m:%d %H:%M:%S')
      rescue
      end
    end
    self.shutter_speed = image['EXIF:ExposureTime'].strip if image['EXIF:ExposureTime']
    self.aperture = image['EXIF:FNumber'].strip if image['EXIF:FNumber']
    self.focal_length = image['EXIF:FocalLengthIn35mmFilm'].strip + (image['EXIF:FocalLengthIn35mmFilm'].strip.empty? ? '' : 'mm') if image['EXIF:FocalLengthIn35mmFilm']
    self.iso = image['EXIF:ISOSpeedRatings'].strip if image['EXIF:ISOSpeedRatings']
    self.exposure_mode = image['EXIF:ExposureProgram'].strip if image['EXIF:ExposureProgram']
    self.flash = image['EXIF:Flash'].strip if image['EXIF:Flash']
    self.exposure_compensation = image['EXIF:ExposureBiasValue'].strip if image['EXIF:ExposureBiasValue']
    self.camera_model = image['EXIF:Model'].strip if image['EXIF:Model']
  end

  def description
    caption.blank? ? img.file.filename : caption
  end

  def next
    gallery.photos.find_by(sequence: sequence + 1)
  end

  def previous
    gallery.photos.find_by(sequence: sequence - 1)
  end

  protected

  def set_defaults
    self.artist = gallery.user.name if artist.blank?
    self.caption = img.model.read_attribute(:img) if caption.blank?
    self.sequence ||= gallery.photos.maximum(:sequence).to_i + 1
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_gallery, only: %i[index create new]
  before_action :set_photo, only: %i[show edit update destroy]

  # GET /galleries/1/photos
  # GET /galleries/1/photos.json
  def index
    @photos = @gallery.photos
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    unless params[:exif]
      @photo.views += 1
      @photo.save
    end

    respond_to do |format|
      format.js { render params[:exif] ? 'exif' : 'show' }
      format.json
    end
  end

  # GET /galleries/1/photos/new
  def new
    @photo = @gallery.photos.new
  end

  # GET /galleries/1/photos/1/edit
  def edit; end

  # POST /galleries/1/photos
  # POST /galleries/1/photos.json
  def create
    @photo = @gallery.photos.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.json { render :show, status: :created, location: @photo }
      else
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
      format.js { render :show }
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    if params[:remove]
      params[:remove].each_key do |key|
        @photo = Photo.find(key)
        @photo.remove_source
        @photo.destroy
      end
    end
    respond_to do |format|
      format.html { redirect_to edit_gallery_path(@gallery), notice: 'photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /photos/increment
  def increment
    @gallery = Gallery.where('code = ?', params[:gallery]).first
    @photo = @gallery.photos.where('img = ?', params[:photo]).first
    @photo.increment
    render nothing: true
  end

  # non-restfull inline editors
  def update_field
    photo = Photo.find(params[:id])
    photo.update(params[:field], params[:value])
    render(text: params[:value])
  end
  # end non-restfull inline editors

  private

  def set_photo
    @photo = Photo.find(params[:id])
    @gallery = @photo.gallery
  end

  def set_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end

  def photo_params
    params.require(:photo).permit(:img, :artist, :caption, :views)
  end

  def create_photo_params
    params.permit(photos: [], photo_names: [], photo_includes: [], photo_artists: [], photo_captions: [])
  end
end

app/views/photos/_add_photos.html.erb
<%= form_tag(gallery_photos_path(@gallery, format: :json), id: 'upload-form', enctype: 'multipart/form-data') do %>
    <%= hidden_field_tag(:gallery_id, @gallery.id) %>
    <div class="row">
        <div class="col">
            <div id="photos-file-input">
                <%= file_field_tag('photos[]', multiple: true, accept: 'image/png,image/gif,image/jpeg') %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="d-inline-flex flex-wrap" id="photos-row"></div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div id="upload-buttons" class="form-buttons d-none form-group text-right p-2 mt-2">
                <%= link_to('cancel', root_path) %>
                <%= submit_tag('upload', id: 'upload-photos-btn', class: 'btn btn-primary') %>
            </div>
        </div>
    </div>
<% end %>

app/views/photos/_exif.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">photo details</h5>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true" aria-label="close">&times;</button>
        </div>
        <div class="modal-body">
            <div class="container" id="exif">
                <div class="row">
                    <div class="col-4 text-right exif-label">viewed:</div><div class="col-8 exif-data"><%= h @photo.views %> times</div>
                </div>
                <div class="row">
                    <div class="col-4 text-right exif-label">aperture:</div><div class="col-8 exif-data"><%= h @photo.aperture %></div>
                </div>
                <div class="row">
                    <div class="col-4 text-right exif-label">date:</div><div class="col-8 exif-data"><%= h @photo.photo_at %></div>
                </div>
                <div class="row">
                    <div class="col-4 text-right exif-label">iso:</div><div class="col-8 exif-data"><%= h @photo.iso %></div>
                </div>
                <div class="row">
                    <div class="col-4 text-right exif-label">mode:</div><div class="col-8 exif-data"><%= h @photo.exposure_mode %></div>
                </div>
                <div class="row">
                    <div class="col-4 text-right exif-label">photographer:</div><div class="col-8 exif-data"><%= h @photo.artist %></div>
                </div>
                <div class="row">
                    <div class="col-4 text-right exif-label">flash:</div><div class="col-8 exif-data"><%= h @photo.flash %></div>
                </div>
                <div class="row">
                    <div class="col-4 text-right exif-label">focal length:</div><div class="col-8 exif-data"><%= h @photo.focal_length %></div>
                </div>
                <div class="row">
                    <div class="col-4 text-right exif-label">compensation:</div><div class="col-8 exif-data"><%= h @photo.exposure_compensation %></div>
                </div>
                <div class="row">
                    <div class="col-4 text-right exif-label">shutter speed:</div><div class="col-8 exif-data"><%= h @photo.shutter_speed %></div>
                </div>
                <div class="row">
                    <div class="col-4 text-right exif-label">camera model:</div><div class="col-8 exif-data"><%= h @photo.camera_model %></div>
                </div> <!-- end .row -->
            </div> <!-- end #exif -->
        </div> <!-- end .modal-body -->
        <div class="modal-footer">
            <a href="#" class="btn btn-secondary" data-dismiss="modal">got it</a>
        </div> <!-- end .modal-footer -->
    </div> <!-- end .modal-content -->
</div> <!-- end .modal-dialog -->

app/views/photos/_form.html.erb
<span class="card mt-2 mr-2">
    <span class="card-body">
        <div class="upload-overlay align-middle text-center d-none"></div>
        <div class="row">
            <div class="col-5 px-1">
                <img height="120" width="120" src="<%= photo.img.url %>" title="<%= photo.img.file.filename %>"/>
            </div>
            <div class="col-7 px-1">
                <input name="photo_names[]" type="text" size="16" value="<%= photo.img.file.filename %>" class="form-control"/>
                <input name="photo_artists[]" type="text" size="16" value="<%= photo.artist %>" class="form-control my-2"/>
                <input name="photo_captions[]" type="text" size="16" value="<%= photo.caption %>" class="form-control my-2"/>
                <input name="photo_includes[]" type="checkbox" checked value="<%= photo.id %>" class="form-control"/>
            </div>
        </div>
    </span>
</span>

app/views/photos/_show.html.erb
<div class="row">
  <div class="col-sm-6 photo-caption">
    <%= p.caption %>
  </div>
</div>
<div class="row">
  <div class="col gallery-photo">
    <%= image_tag(p.img.url, title: p.img.filename) %>
  </div>
</div>
<div class="row">
  <div class="col tools">
    <%= link_to(photo_comments_path(p), class: 'comments-link', remote: true, data: {toggle: 'tooltip', placement: 'top'}, title: "#{p.comments.count} comments") do %>
      <span class="icon-comment"></span>
    <% end %> &#8226;
    <a href="#" data-toggle="tooltip", data-placement="top" title="<%= p.views %> views">
      <span class="icon-view"></span>
    </a> &#8226;
    <%= link_to(photo_path(p, exif: true), class: 'exif-link', remote: true, data: {toggle: 'tooltip', placement: 'top'}, title: 'exif details') do %>
      <span class="icon-exif"></span>
    <% end %> &#8226;
    <%= link_to(p.img_url, class: 'mr-3', data: {toggle: 'tooltip', placement: 'top'}, title: 'download') do %>
      <span class="icon-download"></span>
    <% end %>
    <% if p.previous %>
      <%= link_to(photo_path(p.previous), remote: true, class: 'photo-nav-link previous', data: {toggle: 'tooltip', placement: 'top'}, title: 'previous - arrow keys') do %>
        <span class="icon-previous"></span>
      <% end %>
    <% end %>
    <% if p.next %>
      <%= link_to(photo_path(p.next), remote: true, class: 'photo-nav-link next', data: {toggle: 'tooltip', placement: 'top'}, title: 'next - arrow keys') do %>
        <span class="icon-next"></span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<% form_for(@photo) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :gallery_id %><br />
    <%= f.text_field :gallery_id %>
  </p>
  <p>
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :img %><br />
    <%= f.text_field :img %>
  </p>
  <p>
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/exif.js.erb
jQuery('#gallery-popup').html("<%= escape_javascript(render partial: 'exif') %>").modal('show');

app/views/photos/index.html.erb
<% if (@photos and @photos.size > 0) %>
<table width="100% cellpadding="2" cellspacing="0" class="searchResult">
    <tr>
        <th>artist</th>
        <th>file</th></tr>

    <% @photos.each do |photo| %>
    <tr>
        <td><%=h photo.gallery_id %></td>
        <td><%=h photo.artist %></td>
        <td><%=h photo.img %></td>
        <td><%=h photo.caption %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, :confirm => 'Are you sure?', :method => :delete %></td></tr>
    <% end %>
</table>

<% end %>

<div id="form" class="form">
    <%= render partial: 'form' %>
</div>

app/views/photos/new.html.erb
<div class="row">
    <div class="col">
        <span class="gallery-name"><%= @gallery.name %></span>
        <span class="gallery-date"><%= ": #{@gallery.gallery_on.strftime('%b %d, %Y')}" if @gallery.gallery_on %></span>
    </div>
</div>

<% if @gallery.photos.count > 0 %>
    <div class="row">
        <div class="col">
            <h4><%= @gallery.photos.count %> existing photos</h4>
            <div class="gallery-horiz-thumbnails">
                <% @gallery.photos.each do |p| %>
                    <%= image_tag(p.img_url(:thumb), size: '80x80', class: 'thumbnail', title: p.img.filename) unless p.img.blank? %>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

<div class="row">
    <div class="col">
        <h4>add new photos here</h4>
        <%= render partial: 'add_photos' %>
    </div>
</div>

app/views/photos/show.js.erb
jQuery('.gallery-photo-container').html("<%= escape_javascript(render partial: 'show', locals: { p: @photo }) %>")
$('[data-toggle="tooltip"]').tooltip();

// highlight active thumbnail
$('img.thumbnail').removeClass('active');
$('img[data-sequence="<%= @photo.sequence %>"]').addClass('active');