config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  resources :users
  resources :sessions

  resources :galleries, shallow: true do
    get 'count', on: :member
    resources :photos do
      collection do
        put 'bulkupdate'
      end
      resources :comments
    end
  end

  # match 'photos/update_field/:id/:field' => 'photos#update_field', :as => :caption
  post 'photos/increment'

  get '/:private_key', to: 'galleries#show'

  root to: 'galleries#index'
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :photos, dependent: :delete_all
  belongs_to :user
  belongs_to :default_photo, class_name: 'Photo', optional: true

  validates :code, uniqueness: true

  def self.public_recent
    Gallery.where('private_key is null').order('gallery_on desc').limit(6).all
  end

  def self.search(q, current_user = nil, gallery_on = nil)
    return [] if q.blank?
    galleries = Gallery.where(private_key: q)
    return galleries if galleries.present?
    galleries = Gallery.where(private_key: nil).or(Gallery.where(user: current_user))
    galleries = galleries.where('name like ?', "%#{q}%")
    galleries = galleries.where('gallery_on = ?', gallery_on) if gallery_on
    galleries
  end

  def update_private_key(private_key_param = nil)
    if private_key_param == '1'
      unless private?
        chars = ('a'..'z').to_a + ('1'..'9').to_a
        self.private_key = Array.new(20, '').collect { chars[rand(chars.size)] }.join
      end
    else
      self.private_key = nil
    end
    private_key
  end

  def photo_count
    photos.size
  end

  def private?
    private_key.present?
  end

  def def_photo
    default_photo || photos.first
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: %i[show edit update destroy count]

  # GET /posts
  # GET /posts.json
  def index
    @galleries = if params[:q] # searching
                   Gallery.search(params[:q], current_user).page(params[:page]).per(6)
                 else
                   current_user ? policy_scope(Gallery).order('gallery_on desc').page(params[:page]).per(6) : []
                 end
    @recent_galleries = Gallery.public_recent.all
    redirect_to @galleries.first if @galleries.count == 1
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    unless @gallery
      redirect_to root_path, notice: 'no gallery found'
      return
    end
    # authorize @gallery unless params[:private_key]
    @photos = @gallery.photos.order(:sequence)
    target = policy(@gallery).update? ? new_gallery_photo_path(@gallery) : root_path
    redirect_to target, notice: "#{@gallery.name} is empty" if @photos.blank?
  end

  # GET /posts/new
  def new
    @gallery = Gallery.new
  end

  # GET /posts/1/edit
  def edit
    authorize @gallery
  end

  # GET /posts/1/count.json
  def count
    authorize @gallery
    # @count = @gallery.photo_count
    render json: { gallery_id: @gallery.id, count: @gallery.photo_count }
  end

  # POST /posts
  # POST /posts.json
  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.update_private_key(gallery_params[:private_key])
    @gallery.gallery_on = Time.zone.today if gallery_params[:gallery_on].empty?
    @gallery.user = current_user if current_user

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to new_gallery_photo_path(@gallery), notice: "#{@gallery.name} was successfully created." }
        format.js   { redirect_to new_gallery_photo_path(@gallery, format: :html) }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    gp = gallery_params
    respond_to do |format|
      if @gallery.update(gp.except(:private_key))
        @gallery.update_private_key(gp[:private_key])
        @gallery.save
        format.html { redirect_to @gallery, notice: 'gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: "gallery \"#{@gallery.name}\" was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_gallery
    if params[:private_key]
      @gallery = Gallery.find_by(private_key: params[:private_key])
      return
    end
    @gallery = Gallery.find(params[:id])
  end

  def gallery_params
    params.require(:gallery).permit(:name, :code, :private_key, :user_id, :gallery_on, :default_photo_id)
  end
end

app/helpers/galleries_helper.rb
# view helper for galleries_controller
module GalleriesHelper
  def default_photo(gallery)
    return content_tag(:span, nil, { class: ['icon-gallery', 'empty-gallery-icon'] }, false) if gallery.photos.blank?
    image_tag(gallery.def_photo&.img_url(:thumb), class: 'thumbnail')
  end
end

app/views/galleries/_form.html.erb
<%= form_with(model: @gallery, local: true) do |form| %>
    <div class="form-group row">
        <%= form.label(:name, class: 'col-sm-2 col-form-label text-right') %>
        <div class="col-sm-3">
            <%= form.text_field(:name, class: 'form-control focus') %>
        </div>
        <%= form.label(:code, class: 'col-sm-2 col-form-label text-right') %>
        <div class="col-sm-3">
            <%= form.text_field(:code, class: 'form-control') %>
        </div>
    </div>

    <div class="form-group row">
        <%= form.label(:gallery_on, class: 'col-sm-2 col-form-label text-right') %>
        <div class="col-sm-3">
            <%= form.text_field(:gallery_on, placeholder: Date.today.strftime("%Y-%m-%d"), id: 'gallery-gallery-on', class: 'form-control') %>
        </div>
        <%= form.label(:default_photo, class: 'col-sm-2 col-form-label text-right') %>
        <div class="col-sm-3">
            <%= collection_select(:gallery, :default_photo_id, @gallery.photos, :id, :description, {}, { class: 'form-control' }) %>
        </div>
    </div>
    <div class="form-group row">
        <%= form.label(:private_key, 'private?', class: 'col-sm-2 col-form-label text-right') %>
        <div class="col-sm-3">
            <%= form.check_box(:private_key, id: 'gallery_private_key', class: 'form-control mt-2', checked: @gallery.private?) %>
        </div>
    </div>
    <div class="form-group row">
        <div class="col">
            <div class="text-right form-buttons p-2">
                <%= link_to('cancel', root_path) %>
                <%= form.submit(@gallery.new_record? ? 'create' : 'update', class: 'btn btn-primary') %>
            </div>
        </div>
    </div>
<% end %>

app/views/galleries/_summary.html.erb
<div class="gallery-summary row">
    <div class="col-2">
        <%= default_photo(gallery) %>
    </div>
    <div class="col-10 gallery-summary-text">
        <%= link_to(gallery.name, gallery) %><br/>
        <%= gallery.photo_count %> photos :: <%= gallery.gallery_on.strftime("%b %d, %Y") %>
        <div>
            <% if policy(gallery).edit? %>
                <%= link_to(edit_gallery_path(gallery), data: {toggle: 'tooltip', placement: 'top'}, title: 'edit') do %>
                    <span class="icon-edit text-success"></span>
                <% end %>
                <%= link_to(new_gallery_photo_path(gallery), data: {toggle: 'tooltip', placement: 'top'}, title: 'add photos') do %>
                    <span class="icon-camera"></span>
                <% end %>
            <% end %>
            <% if policy(gallery).destroy? %>
                <%= link_to(gallery_path(gallery), method: :delete, data: {confirm: 'are you sure?', toggle: 'tooltip', placement: 'top'}, title: 'delete') do %>
                      <span class="icon-bin text-danger"></span>
                <% end %>
            <% end %>
            <%= link_to('sharing url', "#{root_url}#{gallery.private_key}") if gallery.private? %>
        </div>
    </div>
</div>

app/views/galleries/_thumbnails.html.erb
<%= link_to(photo_path(p), remote: true) do %>
  <%= image_tag(p.img_url(:thumb), size: '80x80', class: 'thumbnail', title: p.img.filename, data: { sequence: p.sequence }) %>
<% end if p.img.present? %>

app/views/galleries/edit.html.erb
<div class="row">
    <div class="col">
        <span class="gallery-name"><%= @gallery.name %></span>
        <span class="gallery-date"><%= ": #{@gallery.gallery_on.strftime('%b %d, %Y')}" if @gallery.gallery_on %></span>
    </div>
</div>

<div class="row">
    <div class="col">
        <%= render 'form' %>
    </div>
</div>

<%= form_with(model: @gallery, id: 'update-existing-form') do |form| %>
    <div class="row">
        <div class="col">
            <h2>existing photos</h2>
            <div class="d-inline-flex flex-wrap" id="existing-photos-row">
                <%= render partial: 'photos/form', collection: @gallery.photos, as: :photo %>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            <div class="text-right form-buttons p-2">
                <%= link_to('cancel', root_path) %>
                <%= form.submit('update photos', class: 'btn btn-primary') %>
            </div>
        </div>
    </div>
<% end %>

<div class="row">
    <div class="col">
        <h2>add more photos</h2>
        <%= render partial: 'photos/add_photos' %>
    </div>
</div>

app/views/galleries/index.html.erb
<div class="row">
    <div class="col-md-6">
        <div class="card gallery-list">
            <h3 class="card-header bg-light">recent public galleries</h3>
            <div class="card-body">
                <% if @recent_galleries.present? %>
                        <%= render partial: 'summary', collection: @recent_galleries, as: :gallery %>
                <% else %>
                    none
                <% end %>
            </div>
        </div>
    </div> <!-- end .col-md-6 -->
    <div class="col-md-6">
        <div class="card bg-light gallery-list">
            <h3 class="card-header"><%= params[:q] ? 'search results' : 'my galleries' %></h3>
            <div class="card-body">
                <% if @galleries.present? %>
                        <%= render partial: 'summary', collection: @galleries, as: :gallery %>
                    <%= paginate(@galleries, window: 2, outer_window: 1) %>
                <% else %>
                    none
                <% end %>
            </div>
            <% if policy(Gallery).create? %>
                <div class="card-footer text-right">
                    <%= link_to('New Gallery', new_gallery_path, class: 'btn btn-primary') %>
                </div>
            <% end %>
        </div>
    </div> <!-- end .col-md-6 -->
</div> <!-- end .row -->

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

app/views/galleries/show.html.erb
<div class="row">
    <div class="col">
        <span class="gallery-name"><%= @gallery.name %></span>
        <span class="gallery-date">
            <%= ": #{@gallery.gallery_on.strftime('%b %d, %Y')}" if @gallery.gallery_on %>
            <% if policy(@gallery).edit? %>
                <%= link_to(edit_gallery_path(@gallery), data: {toggle: 'tooltip', placement: 'top'}, title: 'edit') do %>
                    <span class="icon-edit"></span>
                <% end %>
                <%= link_to(new_gallery_photo_path(@gallery), data: {toggle: 'tooltip', placement: 'top'}, title: 'add photos') do %>
                    <span class="icon-camera"></span>
                <% end %>
            <% end %>
        </span>
    </div> <!-- end #gallery-info -->
</div> <!-- end row -->

<div class="row">
    <div class="col-3">
        <div class="d-inline-flex flex-wrap gallery-thumbnails">
            <%= render(partial: 'thumbnails', collection: @photos, as: :p) %>
        </div><!-- end .gallery-thumbnails -->
    </div>
    <div class="col-9 gallery-photo-container">
        <%= render(partial: 'photos/show', locals: { p: @gallery.def_photo }) %>
    </div> <!-- end .gallery-photo-container -->
</div> <!-- end row -->

<div id="gallery-popup" role="dialog" class="modal fade"></div>

<%= javascript_tag do %>
    // highlight first thumbnail
    $('img[data-sequence="<%= @gallery.def_photo.sequence %>"]').addClass('active');
<% end %>