config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  resources :users
  resources :sessions

  resources :galleries, shallow: true do
    get 'count', on: :member
    resources :photos do
      collection do
        put 'bulkupdate'
      end
      resources :comments
    end
  end

  # match 'photos/update_field/:id/:field' => 'photos#update_field', :as => :caption
  post 'photos/increment'

  get '/:private_key', to: 'galleries#show'

  root to: 'galleries#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>raceweb - photo</title>
    <meta name="description" content="raceweb photo galleries"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="shortcut icon" href="/favicon.ico" />
    <%= csrf_meta_tags %>
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag controller_name %>
    <% if Rails.env.production? %>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-83838015-2"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'UA-83838015-2');
        </script>
    <% end %>
</head>
<body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <%= link_to('raceweb photo', root_path, class: 'navbar-brand') %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar01" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbar01" class="collapse navbar-collapse">
            <div class="mr-auto"></div>
            <%= form_tag(galleries_path, method: 'get', class: 'form-inline search-form') do %>
                <%= hidden_field_tag :direction, params[:direction] %>
                <%= hidden_field_tag :sort, params[:sort] %>
                <%= search_field_tag(:q, params[:q], placeholder: 'find a gallery', class: 'form-control') %>
            <% end %>

            <ul class="navbar-nav my-2 my-md-0">
                <% if current_user %>
                    <li class="nav-item"><a class="nav-link" href="#">Welcome, <%= current_user.email %></a></li>
                    <li class="nav-item"><%= link_to'logout', logout_path, class: 'nav-link' %></li>
                <% else %>
                    <li class="nav-item"><%= link_to 'register', signup_path, class: 'nav-link', remote: true %></li>
                    <li class="nav-item"><%= link_to 'login', login_path, class: 'nav-link', remote: true %></li>
                <% end %>
            </ul>
        </div><!--/.nav-collapse -->
    </nav>

    <div class="container-fluid">
        <% flash.each do |key, value| %>
            <% type = 'success' if key == 'notice'; type = 'danger' if key == 'alert'; %>
            <div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
                <strong><%= key.capitalize %>:</strong> <%= value %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <% end %>
        <!-- MAIN CONTENT -->
        <%= yield %>
        <!-- END MAIN CONTENT -->
    </div> <!-- end container-fluid -->

    <footer>
        <div class="text-left">
            <!--
            <script type="text/javascript">
            google_ad_client = "ca-pub-2435759852249095";
            google_ad_slot = "2751979843";
            google_ad_width = 468;
            google_ad_height = 60;
            </script>
            <script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
            -->
        </div>
        <div class="copy">
            &copy; <%= Date.today.year %> <a href="mailto:info@raceweb.ca" rel="tooltip" title="email address">raceweb.ca</a>
        </div>
        <div class="clear"></div>
    </footer> <!-- end footer -->

    <!-- hidden modal forms -->
    <div id="registration-form" class="modal hide fade"></div>
    <div id="login-form" class="modal hide"></div>
</body>
</html>